DROP DATABASE BOSS;

CREATE DATABASE BOSS default character set utf8mb4 collate utf8mb4_general_ci;
SET NAMES utf8mb4;
USE BOSS;

-- 會員資料;
CREATE TABLE MEMBER(
  ID VARCHAR(20) PRIMARY KEY,
  Password VARCHAR(20) NOT NULL,
  Email VARCHAR(30) NOT NULL,
  Phone VARCHAR(10) NOT NULL,
  RegDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Birth DATE,
  Gender ENUM('M', 'F', 'N'),
  Address VARCHAR(100),
  Position ENUM('S', 'A', 'C') NOT NULL
);

-- 商品;
CREATE TABLE PRODUCT(
  ID INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(30) NOT NULL,
  State ENUM('in_stock', 'out_of_stock'),
  Stock INT(7) UNSIGNED NOT NULL,
  Price INT(10) UNSIGNED NOT NULL,
  Img VARCHAR(100) NOT NULL,
  Info VARCHAR(300),
  DID INT(7) UNSIGNED,
  CategoryID INT(7) UNSIGNED NOT NULL
);

-- 商品類型;
CREATE TABLE CATAGORY(
  ID INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  PID INT(7) UNSIGNED NOT NULL,
  Name VARCHAR(10) NOT NULL UNIQUE
);

-- 訂單;
CREATE TABLE ORDER_LIST (
  ID INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Date DATETIME NOT NULL,
  Final_Cost INT(7) UNSIGNED NOT NULL,
  State ENUM('submitted', 'processed', 'delivered', 'completed'),
  CID VARCHAR(30) NOT NULL,
  DID INT(7) UNSIGNED NOT NULL,
  SID INT(7) UNSIGNED NOT NULL,
  PID INT(7) UNSIGNED NOT NULL
);

-- 訂單和商品的特殊性關係;
CREATE TABLE ORDER_LIST_RECORD (
  OID INT(7) UNSIGNED NOT NULL,
  PID INT(7) UNSIGNED NOT NULL,
  Quantity INT(7) UNSIGNED NOT NULL,
  PRIMARY KEY (OID, PID)
);

-- 購物車;
CREATE TABLE CART (
  ID INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CID VARCHAR(30) NOT NULL,
  PID INT(7) UNSIGNED NOT NULL
);

-- 購物車和商品的特殊性關係;
CREATE TABLE CART_RECORD (
  ID INT(7) UNSIGNED,
  PID INT(7) UNSIGNED,
  Quantity INT(5) UNSIGNED NOT NULL,
  PRIMARY KEY(ID,PID)
);

-- 評論;
CREATE TABLE COMMENT (
  ID INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CID VARCHAR(30) NOT NULL,
  PID INT(7) UNSIGNED NOT NULL,
  Star INT(1) NOT NULL,
  Comment VARCHAR(100) NOT NULL
);

-- 折扣;
CREATE TABLE DISCOUNT (
  ID INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Type ENUM('shipping', 'seasoning', 'event'),
  PeriodFrom DATETIME NOT NULL,
  PeriodTo DATETIME NOT NULL,
  Requirement INT(7) UNSIGNED,
  Rate DOUBLE(3,3) NOT NULL,
  EventType ENUM('BOGO', 'discount')
);

-- 插入測試用範例資料;
INSERT INTO PRODUCT (Name, Price, State, Stock, DID, CategoryID, Info, Img)
VALUE('純喫茶 綠茶', 25, 'in_stock', 999, NULL, 0, '採集新鮮茶葉進行炒菁，呈現茶葉鮮綠與清香，搭配柔和的茉莉綠茶，口味清爽不甜膩，新鮮暢飲最過癮!', 'http://www.pecos.com.tw/tmp/image/20140409/20140409202153_39623.jpg'),
VALUE('純喫茶 紅茶', 25, 'in_stock', 999, NULL, 0, '以焙炒大麥搭配紅茶，調製出濃香十足的台灣味紅茶，滿足你對新鮮的期望！', 'http://www.pecos.com.tw/tmp/image/20140409/20140409202109_56209.jpg'),
VALUE('純喫茶 檸檬紅茶', 25, 'in_stock', 999, NULL, 0, '以冰析鮮萃工法，保留檸檬的香氣，搭配濃郁甘醇的紅茶，調和出新鮮的酸甜好滋味！', 'http://www.pecos.com.tw/tmp/image/20140417/20140417192522_66698.jpg'),
VALUE('純喫茶 烏龍青茶', 25, 'in_stock', 999, NULL, 0, '添加焙火烏龍茶，釋放豐富香氣與醇厚原味，多層次的獨特茶感，甘潤無窮！', 'http://www.pecos.com.tw/tmp/image/20140409/20140409202049_34108.jpg'),
VALUE('純喫茶 鮮柚綠茶', 25, 'in_stock', 999, NULL, 0, '以冰析鮮萃工法，保留葡萄柚香氣，調和清爽甘醇的茉莉綠茶，激盪出酸甜清香的新鮮果茶風味！', 'http://www.pecos.com.tw/tmp/image/20150105/20150105090925_79899.jpg'),
VALUE('純喫茶 無糖綠茶', 25, 'in_stock', 999, NULL, 0, '採集新鮮茶葉，以冰析鮮萃工法保留新鮮茶香及兒茶素，茶感清香回韻，讓原味更新鮮！', 'http://www.pecos.com.tw/tmp/image/20160130/20160130103658_89475.jpg');


-- FOREIGN KEY;
ALTER TABLE PRODUCT ADD FOREIGN KEY (DID) REFERENCES DISCOUNT (ID);
ALTER TABLE PRODUCT ADD FOREIGN KEY (CategoryID) REFERENCES CATAGORY(ID);
ALTER TABLE ORDER_LIST ADD FOREIGN KEY (CID) REFERENCES MEMBER(ID);
ALTER TABLE ORDER_LIST ADD FOREIGN KEY (DID) REFERENCES DISCOUNT(ID);
ALTER TABLE ORDER_LIST_RECORD ADD FOREIGN KEY (OID) REFERENCES ORDER_LIST(ID);
ALTER TABLE ORDER_LIST_RECORD ADD FOREIGN KEY (PID) REFERENCES PRODUCT(ID);
ALTER TABLE CART ADD FOREIGN KEY (CID) REFERENCES MEMBER(ID);
ALTER TABLE CART_RECORD ADD FOREIGN KEY (ID) REFERENCES CART(ID);
ALTER TABLE CART_RECORD ADD FOREIGN KEY (PID) REFERENCES PRODUCT(ID);
ALTER TABLE COMMENT ADD FOREIGN KEY (CID) REFERENCES MEMBER(ID);
