DROP DATABASE BOSS;

CREATE DATABASE BOSS default character set utf8mb4 collate utf8mb4_general_ci;
SET NAMES utf8mb4;
USE BOSS;

-- 會員資料;
CREATE TABLE MEMBER(
  ID VARCHAR(20) PRIMARY KEY,
  Password VARCHAR(20) NOT NULL,
  Email VARCHAR(30) NOT NULL,
  Phone VARCHAR(10) NOT NULL,
  RegDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Birth DATE,
  Gender ENUM('M', 'F', 'N'),
  Address VARCHAR(100),
  Position ENUM('S', 'A', 'C') NOT NULL
);

CREATE TABLE PRODUCT(
  ID INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(30) NOT NULL,
  State ENUM(' ', ' ', ' '),
  Stock INT(7) UNSIGNED NOT NULL,
  Price INT(10) UNSIGNED NOT NULL,
  Img VARCHAR(100) NOT NULL,
  Description VARCHAR(300),
  DID INT(7) UNSIGNED NOT NULL,
  CategoryID INT(7) UNSIGNED NOT NULL
);

-- 商品類型;
CREATE TABLE CATAGORY(
  ID INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  PID INT(7) UNSIGNED NOT NULL,
  Name VARCHAR(10) NOT NULL UNIQUE
);

-- 訂單;
CREATE TABLE ORDER_LIST (
  ID INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Date DATETIME NOT NULL,
  Final_Cost INT(7) UNSIGNED NOT NULL,
  State ENUM('submitted', 'processed', 'delivered', 'completed'),
  CID VARCHAR(30) NOT NULL,
  DID INT(7) UNSIGNED NOT NULL,
  SID INT(7) UNSIGNED NOT NULL,
  PID INT(7) UNSIGNED NOT NULL
);

CREATE TABLE ORDER_LIST_RECORD (
  OID INT(7) UNSIGNED NOT NULL,
  PID INT(7) UNSIGNED NOT NULL,
  Quantity INT(7) UNSIGNED NOT NULL,
  PRIMARY KEY (OID, PID)
);

-- 購物車;
CREATE TABLE CART (
  ID INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CID VARCHAR(30) NOT NULL,
  PID INT(7) UNSIGNED NOT NULL
);

-- 購物車紀錄
CREATE TABLE CART_RECORD (
  ID INT(7) UNSIGNED,
  PID INT(7) UNSIGNED,
  Quantity INT(5) UNSIGNED NOT NULL,
  PRIMARY KEY(ID,PID)
);

-- 評論;
CREATE TABLE COMMENT (
  ID INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CID VARCHAR(30) NOT NULL,
  PID INT(7) UNSIGNED NOT NULL,
  Star INT(1) NOT NULL,
  Comment VARCHAR(100) NOT NULL
);

-- 折扣
CREATE TABLE DISCOUNT (
  ID INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Type ENUM('shipping', 'seasoning', 'event'),
  PeriodFrom DATETIME NOT NULL,
  PeriodTo DATETIME NOT NULL,
  Requirement INT(7) UNSIGNED,
  Rate DOUBLE(3,3) NOT NULL,
  EventType ENUM('BOGO', 'discount')
);

ALTER TABLE PRODUCT ADD FOREIGN KEY (DID) REFERENCES DISCOUNT (ID);
ALTER TABLE PRODUCT ADD FOREIGN KEY (CategoryID) REFERENCES CATAGORY(ID);
ALTER TABLE ORDER_LIST ADD FOREIGN KEY (CID) REFERENCES MEMBER(ID);
ALTER TABLE ORDER_LIST ADD FOREIGN KEY (DID) REFERENCES DISCOUNT(ID);
ALTER TABLE ORDER_LIST_RECORD ADD FOREIGN KEY (OID) REFERENCES ORDER_LIST(ID);
ALTER TABLE ORDER_LIST_RECORD ADD FOREIGN KEY (PID) REFERENCES PRODUCT(ID);
ALTER TABLE CART ADD FOREIGN KEY (CID) REFERENCES MEMBER(ID);
ALTER TABLE CART_RECORD ADD FOREIGN KEY (ID) REFERENCES CART(ID);
ALTER TABLE CART_RECORD ADD FOREIGN KEY (PID) REFERENCES PRODUCT(ID);
ALTER TABLE COMMENT ADD FOREIGN KEY (CID) REFERENCES MEMBER(ID);
