CREATE DATABASE BOSS default character set utf8 collate utf8_general_ci;
SET NAMES utf8;
USE BOSS;


-- 會員資料;
CREATE TABLE MEMBER(
  ID VARCHAR(20) PRIMARY KEY,
  Password VARCHAR(20) NOT NULL,
  Email VARCHAR(30) NOT NULL,
  Phone VARCHAR(10) NOT NULL,
  RegDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Birth DATE,
  Gender ENUM('M', 'F', 'N'),
  Address VARCHAR(100),
  Position ENUM('S', 'A', 'C') NOT NULL
);


CREATE TABLE PRODUCT(
  ID VARCHAR(20) PRIMARY KEY,
  Password VARCHAR(20) NOT NULL,
  Email VARCHAR(30) NOT NULL,
  Phone VARCHAR(10) NOT NULL,
  RegDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  Birth DATE,
  Gender ENUM('M', 'F', 'N'),
  Address VARCHAR(100),
  Position ENUM('S', 'A', 'C') NOT NULL
);

-- 商品類型;
CREATE TABLE CATAGORY(
  ID INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(10) NOT NULL UNIQUE
);

-- 訂單;
CREATE TABLE ORDER_LIST (
  ID INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Date DATETIME NOT NULL,
  Final_Cost INT(7) UNSIGNED NOT NULL,
  State ENUM('submitted', 'processed', 'delivered', 'completed'),
  CID VARCHAR(30) NOT NULL,
  DID INT(7) UNSIGNED NOT NULL,
  SID INT(7) UNSIGNED NOT NULL,
  FOREIGN KEY (CID) REFERENCES MEMBER(ID)
);

-- 購物車;
CREATE TABLE CART (
  ID INT(7) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  CID VARCHAR(30) NOT NULL,
  PID INT(7) UNSIGNED NOT NULL,
  FOREIGN KEY (CID) REFERENCES MEMBER(ID)
);
